name: melindakausek
favicon: null
layout_spectrum: 0.5522120846435428
typography_spectrum: 0.46308532706461847
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9002482900395989
  lightness: 0.1787602538242936
  saturation: 0.672454658197239
  rhythmicContrast: 0.5381963152904063
purpose: []
